[default_session]
startup_command = "source ~/.config/sesh/bin/default.sh"


[[session]]
name = "sesh"
path = "~/git_repos/sesh"
startup_command = "source ~/.config/sesh/bin/sesh.sh"

[[session]]
name = "db"
path = "/tmp"
startup_command = "nvim -c DBUI"
