add_newline = true

format = """
$character\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$golang\
[ > ](bold white)\
"""

[git_branch]
disabled = true

[git_status]
disabled = true

[directory]
format = "[ $path]($style)"
style = "#41a6b5"

[character]
success_symbol = " [îš‘](bold white)"
error_symbol = " [îš‘](bold red)"
vimcmd_symbol = " [î˜«](bold green)"
vimcmd_replace_one_symbol = " [î˜«](bold purple)"
vimcmd_replace_symbol = " [î˜«](bold purple)"
vimcmd_visual_symbol = " [î˜«](bold yellow)"

[python]
format = '[ ğŸ ($virtualenv)](purple)'

[nodejs]
format = '[ ğŸ¤– $version](purple) '

[golang]
format = '[ ğŸğŸ’¨ $version](purple) '
